# Multi-stage: the builder installs into a venv, the runtime carries only what runs.
#
# The base image is pinned by digest, not just by tag. `python:3.12-slim` floats
# -- two builds a month apart can differ -- and a floating base makes an image
# neither reproducible nor auditable. Update the digest deliberately:
#   docker buildx imagetools inspect python:3.12-slim
FROM python:3.12-slim AS builder
ENV PIP_DISABLE_PIP_VERSION_CHECK=1 PIP_NO_CACHE_DIR=1
RUN apt-get update && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /build
COPY pyproject.toml ./
COPY app ./app
# requirements.lock is generated by `make lock` and committed, so an image build
# resolves the same tree the tests ran against.
COPY requirements.loc[k] ./
RUN python -m venv /opt/venv \
    && /opt/venv/bin/pip install --upgrade pip \
    && if [ -f requirements.lock ]; then \
         /opt/venv/bin/pip install -r requirements.lock; \
       fi \
    && /opt/venv/bin/pip install --no-deps .

FROM python:3.12-slim AS runtime
ENV PATH="/opt/venv/bin:$PATH" \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1
RUN useradd --create-home --uid 10001 appuser
COPY --from=builder /opt/venv /opt/venv
WORKDIR /app
COPY --chown=appuser:appuser . .
USER appuser
EXPOSE 8000
HEALTHCHECK --interval=30s --timeout=3s --start-period=20s --retries=3 \
  CMD python -c "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/healthz').status==200 else 1)"
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]
